import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from './_components/header/page'
import { AntdRegistry } from '@ant-design/nextjs-registry'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <header className="sticky top-0">
          <Header />
        </header>
        <article className="h-[calc(100vh-80px-48px)]  pr-[90px] pl-[90px] pt-[90px]">
          <AntdRegistry>{children}</AntdRegistry>
        </article>
        <footer className="h-[48px] flex justify-center items-center text-gray-400 text-sm bg-[#f5f5f5]">
          @联系我: XXXXXXX
        </footer>
      </body>
    </html>
  )
}
